version: "3.8"
services:
  mysql:
    image: postgres:16-alpine
    container_name: postgres_backend
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 5432:5432
